package middleware

import (
	"net/http"
)

// SetRequestID is a middleware that sets the X-Request-ID header to the
// id generated by idGenerator.
func SetRequestID(idGenerator func() string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Header.Get("X-Request-ID") == "" {
				r.Header.Set("X-Request-ID", idGenerator())
			}
			next.ServeHTTP(w, r)
		})
	}
}
